export const IMAGE_PATHS = {
PROFILEPIC: "/image/ProfilePic.jpg",
PROFILEPIC1: "/image/ProfilePic1.png",
PROFILEPICS: "/image/ProfilePicS.png",
PROFILEPICS1: "/image/ProfilePicS1.png",
HTML: "/image/Html.png",
CSS: "/image/Css.png",
JAVASCRIPT: "/image/JavaScript.png",
REACT: "/image/React.png",
NEXTJS: "/image/Nextjs.png",
TAILWIND: "/image/Tailwind.png",
NODEJS: "/image/Nodejs.png",
VSCODE: "/image/Vscode.png",
PROJECTIMG: "/image/ProjectImg.png",
DMOVIES: "/image/DMovies.png",
FRIENDCHAT: "/image/Freind_Chat.png",
ECOWEB: "/image/Eco.png",
GITHUB: "/image/Github.png",
MONGODB: "/image/MONGODB.png",
BOOTSTRAP: "/image/bootstrap.png",
FIREBASE: "/image/Firebase.png",
};